spring:
  data:
    mongodb:
#      ${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOSTNAME}:${MONGO_PORT}/${MONGO_DB}?authSource=writeapp&w=1
#      mongodb://<username>:<password>@<host>:<port>/<database>
      uri: mongodb://teixeira:teixeira@localhost:27017/teixeira?authSource=admin
      auto-index-creation: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
      mongo:
        enabled: true
      show-components: always